---
title: "Synchrony from multivariate models"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Teresa Bohner"
date: "3/19/2020"
output: 
  html_document:
    toc: true
    collapsed: false
    toc_float: true
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(brms)
library(tidybayes)
library(scales)
library(cowplot)
```

## Overview

Synchrony is explored here through residual correlations betweeen trees from multivariate models of tree growth.
```{r data}
precip <- read.csv("Processed Data/precip_temp_spei.csv")
rings_field <- read.csv("Processed Data/matched_rings_field.csv")  %>% 
  left_join(precip) %>% 
  group_by(Site, Neighborhood, Species) %>% 
  mutate(treeID=as.numeric(droplevels(as.factor(tree.uniqueID)))) %>% ## counter id if we want it rather than unique ID
  arrange(Site, Neighborhood, Species, ID)

region <- rings_field %>% 
  ungroup() %>% 
  dplyr::select(c(Site, Region, hilo)) %>% 
  group_by(Site) %>% 
  summarize_all(first)

ids <- ungroup(rings_field) %>% 
  dplyr::select(c(Site, Neighborhood, tree.uniqueID)) %>% 
  group_by(Site, Neighborhood, tree.uniqueID) %>%  summarize_all(first)



  
  
```

```{r models}
## load all of the brms models
for(i in unique(rings_field$Site)) {
  for(j in unique(rings_field$Neighborhood)){
    assign(paste0("fit", i, j), readRDS(paste0("saved models/with covar/fit", i, j, ".rds")), envir = .GlobalEnv)
  }
}

```


``` {r funs_and_manip}
## function to extract the residual correlations----
cor_extract <- function(mod) {
  vars <- mod %>% 
  gather_draws(`rescor.*`, regex=T) %>% 
  median_qi() %>% 
  filter(str_detect(.variable, "pptmm")==FALSE) %>% 
  mutate(
    tree1=str_sub(str_split_fixed(.variable, "__", 3)[,2], start=2),
    spp1=ifelse(str_detect(tree1, "ac")==TRUE, "ac", 
                ifelse(str_detect(tree1, "pj")==TRUE, "pj", 
                       ifelse(str_detect(tree1, "pl")==TRUE, "pl", 
                              ifelse(str_detect(tree1, "pp")==TRUE, "pp", "am")))),
    tree2=str_sub(str_split_fixed(.variable, "__", 3)[,3], start=2),
    spp2=ifelse(str_detect(tree2, "ac")==TRUE, "ac", 
                ifelse(str_detect(tree2, "pj")==TRUE, "pj", 
                       ifelse(str_detect(tree2, "pl")==TRUE, "pl", 
                              ifelse(str_detect(tree2, "pp")==TRUE, "pp", "am")))),
    pair=str_c(spp1, spp2, sep="-"),
    comp=ifelse(spp1==spp2, "intra", "inter"),
    Site=i,
    Neighborhood=j) 
}


## extract the residual correlations for each model----
for(i in sort(unique(rings_field$Site))) {
  for(j in sort(unique(rings_field$Neighborhood))){
    # print(paste0(i,j))
    mod <- get(paste0("fit", i, j))
    vars <- cor_extract(mod)

    if(i=="bm"&j==1){
      bigvars <- vars
    } else bigvars <- bind_rows(bigvars, vars)
  }
}

bigvars2 <- filter(bigvars, Site!="ic")

## summary data for median correlation
summary <- group_by(bigvars2, spp1, spp2, comp) %>% 
  summarise(med=median(.value))

## function to keep all draws of residual correlations----
keep_draws <- function(mod) {
  vars <- mod %>% 
  gather_draws(`rescor.*`, regex=T) %>% 
  # filter(str_detect(.variable, "pptmm")==FALSE) %>% 
  mutate(
    tree1=str_sub(str_split_fixed(.variable, "__", 3)[,2], start=2),
    spp1=ifelse(str_detect(tree1, "ac")==TRUE, "ac",
                ifelse(str_detect(tree1, "pj")==TRUE, "pj",
                       ifelse(str_detect(tree1, "pl")==TRUE, "pl",
                              ifelse(str_detect(tree1, "pp")==TRUE, "pp", "am")))),
    tree2=str_sub(str_split_fixed(.variable, "__", 3)[,3], start=2),
    spp2=ifelse(str_detect(tree2, "ac")==TRUE, "ac",
                ifelse(str_detect(tree2, "pj")==TRUE, "pj",
                       ifelse(str_detect(tree2, "pl")==TRUE, "pl",
                              ifelse(str_detect(tree2, "pp")==TRUE, "pp", "am")))),
    pair=str_c(spp1, spp2, sep="-"),
    comp=ifelse(spp1==spp2, "intra", "inter"),
    Site=i,
    Neighborhood=j)
}

for(i in sort(unique(rings_field$Site))) {
  for(j in sort(unique(rings_field$Neighborhood))){
    # print(paste0(i,j))
    mod <- get(paste0("fit", i, j))
    draws <- keep_draws(mod)

    if(i=="bm"&j==1){
      bigdraws <- draws
    } else bigdraws <- bind_rows(bigdraws, draws)
  }
}

bigdraws2 <- filter(bigdraws, Site!="ic")

## summary data for median correlation----
summary2 <- group_by(bigvars2, spp1, spp2, comp) %>% 
  summarise(med=median(.value))

## function to extract data at the species level----
spp_subsetter <- function(data, sp) {
  a <- filter(data, pair==paste(sort(c(sp, "ac")), collapse="-")) %>%
    mutate(focal_sp=sp,
           comp_sp="ac")
  b <- filter(data, pair==paste(sort(c(sp, "pj")), collapse="-")) %>%
    mutate(focal_sp=sp,
           comp_sp="pj")
  c <- filter(data, pair==paste(sort(c(sp, "pl")), collapse="-")) %>%
    mutate(focal_sp=sp,
           comp_sp="pl")
  d <- filter(data, pair==paste(sort(c(sp, "pp")), collapse="-")) %>%
    mutate(focal_sp=sp,
           comp_sp="pp")
  
  bind_rows(a,b,c,d) %>%
    mutate(comp_sp=ifelse(comp_sp==focal_sp, "self", comp_sp))
}

## subset species----
acdat <- spp_subsetter(bigvars2, "ac")
pjdat <- spp_subsetter(bigvars2, "pj")
pldat <- spp_subsetter(bigvars2, "pl")
ppdat <- spp_subsetter(bigvars2, "pp")

acdat <- spp_subsetter(bigdraws2, "ac")
pjdat <- spp_subsetter(bigdraws2, "pj")
pldat <- spp_subsetter(bigdraws2, "pl")
ppdat <- spp_subsetter(bigdraws2, "pp")

```

compare distributions maintaining all of the draws or just summarizing the medians from each individual pair
```{r fig}

## matrix style figure
ggplot(bigvars2, aes(.value, color=comp, fill=comp)) +
  geom_density(position = "identity", alpha=0.4) +
  theme_test() +
  geom_vline(data=summary, aes(xintercept = med), linetype="dashed") +
  facet_grid(spp2~spp1)

vars2 <- left_join(bigvars2, region) %>% 
  left_join(dist)

ggplot(filter(vars2, Site=="sl"), aes(Distance, .value, color=comp)) +
  geom_point() +
  geom_smooth(method='lm', se=F) +
  facet_grid(spp2~spp1)
  
ggplot(bigdraws2, aes(.value, color=comp, fill=comp)) +
  geom_density(position = "identity", alpha=0.4) +
  theme_test() +
  geom_vline(data=summary2, aes(xintercept = med), linetype="dashed") +
  facet_grid(spp2~spp1)

# show_col(viridis_pal()(5)) # get the hex codes for the colors

cols <- c("self"="#440154FF", "pj"="#3B528BFF", "pl"="#21908CFF", "pp"="#5DC863FF", "ac"="#FDE725FF") ## keep species cols consistent

p1 <- ggplot(acdat, aes(.value, color=comp_sp, fill=comp_sp)) +
  geom_density(position = "identity", alpha=0.5) +
  theme_test() +
  ggtitle("A. concolor") +
  scale_fill_manual(values=cols) +
  scale_color_manual(values=cols) +
  theme(legend.position = 'none') +
  xlab("Correlation")

acdat2 <- left_join(acdat, region) 

ggplot(acdat2, aes(.value, color=comp_sp, fill=comp_sp)) +
  geom_density(position = "identity", alpha=0.5) +
  theme_test() +
  ggtitle("A. concolor") +
  scale_fill_manual(values=cols) +
  scale_color_manual(values=cols) +
  theme(legend.position = 'none') +
  facet_grid(Region~hilo)+
  xlab("Correlation")

p2 <- ggplot(pjdat, aes(.value, color=comp_sp, fill=comp_sp)) +
  geom_density(position = "identity", alpha=0.5) +
  theme_test() +
  ggtitle("P. jeffreyi") +
  scale_fill_manual(values=cols) +
  scale_color_manual(values=cols) +
  theme(legend.position = 'none') +
  xlab("Correlation")

p3 <- ggplot(pldat, aes(.value, color=comp_sp, fill=comp_sp)) +
  geom_density(position = "identity", alpha=0.5) +
  theme_test() +
  ggtitle("P. lambertiana") +
  scale_fill_manual(values=cols) +
  scale_color_manual(values=cols) +
  theme(legend.position = 'none') +
  xlab("Correlation")

p4 <- ggplot(ppdat, aes(.value, color=comp_sp, fill=comp_sp)) +
  geom_density(position = "identity", alpha=0.5) +
  theme_test() +
  ggtitle("P. ponderosa") +
  scale_fill_manual(values=cols) +
  scale_color_manual(values=cols) +
  theme(legend.position = 'none') +
  xlab("Correlation")

dummy <- ggplot(bind_rows(acdat, pjdat), aes(.value, color=comp_sp, fill=comp_sp)) +
  geom_density(alpha=0.5) +
  theme_test() +
  ggtitle("P. lambertiana") +
  scale_fill_manual(values=cols) +
  scale_color_manual(values=cols) +
  labs(fill = "Competitor", color="Competitor")

legend <- cowplot::get_legend(dummy)
# plot_grid(legend)

plot_grid(plot_grid(p1,p2,p3,p4, ncol=2), legend, ncol=2, rel_widths = c(1,.2))
```

```{r time_models}
## load all of the brms models
timeseq <- seq(1910, 2010, by=10)
for(i in unique(rings_field$Site)) {
  for(j in unique(rings_field$Neighborhood)){
    for(t in timeseq) {
    assign(paste0("fit", i, j, t), readRDS(paste0("saved models/timeslice/fit", i, j, t, ".rds")), envir = .GlobalEnv)
    }
  }
}

```

``` {r time_funs_and_manip}
## function to extract the residual correlations----
cor_extract2 <- function(mod) {
  vars <- mod %>% 
  gather_draws(`rescor.*`, regex=T) %>% 
  median_qi() %>% 
  filter(str_detect(.variable, "pptmm")==FALSE) %>% 
  mutate(
    tree1=str_sub(str_split_fixed(.variable, "__", 3)[,2], start=2),
    spp1=ifelse(str_detect(tree1, "ac")==TRUE, "ac", 
                ifelse(str_detect(tree1, "pj")==TRUE, "pj", 
                       ifelse(str_detect(tree1, "pl")==TRUE, "pl", 
                              ifelse(str_detect(tree1, "pp")==TRUE, "pp", "am")))),
    tree2=str_sub(str_split_fixed(.variable, "__", 3)[,3], start=2),
    spp2=ifelse(str_detect(tree2, "ac")==TRUE, "ac", 
                ifelse(str_detect(tree2, "pj")==TRUE, "pj", 
                       ifelse(str_detect(tree2, "pl")==TRUE, "pl", 
                              ifelse(str_detect(tree2, "pp")==TRUE, "pp", "am")))),
    pair=str_c(spp1, spp2, sep="-"),
    comp=ifelse(spp1==spp2, "intra", "inter"),
    Site=i,
    Neighborhood=j,
    time=t) 
}


## extract the residual correlations for each model----
for(i in sort(unique(rings_field$Site))) {
  for(j in sort(unique(rings_field$Neighborhood))){
    for(t in timeseq){
         # print(paste0(i,j))
    mod <- get(paste0("fit", i, j, t))
    vars <- cor_extract2(mod)

    if(t==1910){
      bm <- vars
    } else bm <- bind_rows(bm, vars)
    }
 
  }
}


test <- select(bm, c(.value, time)) %>% 
  group_by(time) %>% 
  summarise(.upper=quantile(.value, probs=.975),
            .lower=quantile(.value, probs=.025),
            .value=quantile(.value, probs=.5),
            .width=0.95) %>% 
  mutate_at(vars(time), as.factor)

ggplot(test, aes(y=time, x=.value, upper=.upper, lower=.lower)) +
  geom_pointintervalh()

bigvars2 <- filter(bigvars, Site!="ic")

## summary data for median correlation
summary <- group_by(bigvars2, spp1, spp2, comp) %>% 
  summarise(med=median(.value))

## function to keep all draws of residual correlations----
keep_draws <- function(mod) {
  vars <- mod %>% 
  gather_draws(`rescor.*`, regex=T) %>% 
  # filter(str_detect(.variable, "pptmm")==FALSE) %>% 
  mutate(
    tree1=str_sub(str_split_fixed(.variable, "__", 3)[,2], start=2),
    spp1=ifelse(str_detect(tree1, "ac")==TRUE, "ac",
                ifelse(str_detect(tree1, "pj")==TRUE, "pj",
                       ifelse(str_detect(tree1, "pl")==TRUE, "pl",
                              ifelse(str_detect(tree1, "pp")==TRUE, "pp", "am")))),
    tree2=str_sub(str_split_fixed(.variable, "__", 3)[,3], start=2),
    spp2=ifelse(str_detect(tree2, "ac")==TRUE, "ac",
                ifelse(str_detect(tree2, "pj")==TRUE, "pj",
                       ifelse(str_detect(tree2, "pl")==TRUE, "pl",
                              ifelse(str_detect(tree2, "pp")==TRUE, "pp", "am")))),
    pair=str_c(spp1, spp2, sep="-"),
    comp=ifelse(spp1==spp2, "intra", "inter"),
    Site=i,
    Neighborhood=j)
}

for(i in sort(unique(rings_field$Site))) {
  for(j in sort(unique(rings_field$Neighborhood))){
    # print(paste0(i,j))
    mod <- get(paste0("fit", i, j))
    draws <- keep_draws(mod)

    if(i=="bm"&j==1){
      bigdraws <- draws
    } else bigdraws <- bind_rows(bigdraws, draws)
  }
}

bigdraws2 <- filter(bigdraws, Site!="ic")

## summary data for median correlation----
summary2 <- group_by(bigvars2, spp1, spp2, comp) %>% 
  summarise(med=median(.value))

## function to extract data at the species level----
spp_subsetter <- function(data, sp) {
  a <- filter(data, pair==paste(sort(c(sp, "ac")), collapse="-")) %>%
    mutate(focal_sp=sp,
           comp_sp="ac")
  b <- filter(data, pair==paste(sort(c(sp, "pj")), collapse="-")) %>%
    mutate(focal_sp=sp,
           comp_sp="pj")
  c <- filter(data, pair==paste(sort(c(sp, "pl")), collapse="-")) %>%
    mutate(focal_sp=sp,
           comp_sp="pl")
  d <- filter(data, pair==paste(sort(c(sp, "pp")), collapse="-")) %>%
    mutate(focal_sp=sp,
           comp_sp="pp")
  
  bind_rows(a,b,c,d) %>%
    mutate(comp_sp=ifelse(comp_sp==focal_sp, "self", comp_sp))
}

## subset species----
acdat <- spp_subsetter(bigvars2, "ac")
pjdat <- spp_subsetter(bigvars2, "pj")
pldat <- spp_subsetter(bigvars2, "pl")
ppdat <- spp_subsetter(bigvars2, "pp")

acdat <- spp_subsetter(bigdraws2, "ac")
pjdat <- spp_subsetter(bigdraws2, "pj")
pldat <- spp_subsetter(bigdraws2, "pl")
ppdat <- spp_subsetter(bigdraws2, "pp")

```